version: "2"
services:
  mangmang:
    image: mangmang:latest
    build: .
    container_name: mangmang
    restart: always
    ports:
      - "3010:80"
    links:
      - mangmang-redis
    external_links:
      - qzq-mysql
  mangmang-redis:
    image: redis:alpine
    container_name: mangmang_redis
    restart: always
